# @summary policy configuration section
# @see https://www.knot-dns.cz/docs/latest/html/reference.html#policy-section
type Knot::Policy = Struct[{
  'comment'              => Optional[String[1]],
  'id'                   => String[1],
  'keystore'             => Optional[Array[String[1]]],
  'manual'               => Optional[Boolean],
  'single-type-signing'  => Optional[Boolean],
  'algorithm'            => Optional[Enum['rsasha1', 'rsasha1-nsec3-sha1',
  'rsasha256', 'rsasha512', 'ecdsap256sha256', 'ecdsap384sha384', 'ed25519', 'ed448']],
  'ksk-size'             => Optional[Knot::Subtypes::Size],
  'zsk-size'             => Optional[Knot::Subtypes::Size],
  'ksk-shared'           => Optional[Boolean],
  'dnskey-ttl'           => Optional[Knot::Subtypes::Time],
  'zone-max-ttl'         => Optional[Knot::Subtypes::Time],
  'keytag-modulo'        => Optional[String[1]],
  'ksk-lifetime'         => Optional[Knot::Subtypes::Time],
  'zsk-lifetime'         => Optional[Knot::Subtypes::Time],
  'delete-delay'         => Optional[Knot::Subtypes::Time],
  'propagation-delay'    => Optional[Knot::Subtypes::Time],
  'rrsig-lifetime'       => Optional[Knot::Subtypes::Time],
  'rrsig-refresh'        => Optional[Knot::Subtypes::Time],
  'rrsig-pre-refresh'    => Optional[Knot::Subtypes::Time],
  'reproducible-signing' => Optional[Boolean],
  'nsec3'                => Optional[Boolean],
  'nsec3-iterations'     => Optional[Integer],
  'nsec3-opt-out'        => Optional[Boolean],
  'nsec3-salt-length'    => Optional[Integer],
  'nsec3-salt-lifetime'  => Optional[Knot::Subtypes::Time],
  'signing-threads'      => Optional[Integer],
  'ksk-submission'       => Optional[String[1]],
  'ds-push'              => Optional[Variant[String[1],Array[String[1]]]],
  'cds-cdnskey-publish'  => Optional[Enum['none', 'delete-dnssec', 'rollover', 'always', 'double-ds']],
  'cds-digest-type'      => Optional[Enum['sha256', 'sha384']],
  'dnskey-management'    => Optional[Enum['full', 'incremental']],
  'offline-ksk'          => Optional[Boolean],
  'unsafe-operation'     => Optional[Array[Enum['none', 'no-check-keyset' , 'no-update-dnskey', 'no-update-nsec', 'no-update-expired']]],
}]
